#
#    ░██████╗███╗░░██╗░█████╗░███╗░░░███╗███████╗░█████╗░██╗░░██╗░█████╗░███╗░░██╗░██████╗░███████╗██████╗░
#    ██╔════╝████╗░██║██╔══██╗████╗░████║██╔════╝██╔══██╗██║░░██║██╔══██╗████╗░██║██╔════╝░██╔════╝██╔══██╗
#    ╚█████╗░██╔██╗██║███████║██╔████╔██║█████╗░░██║░░╚═╝███████║███████║██╔██╗██║██║░░██╗░█████╗░░██████╔╝
#    ░╚═══██╗██║╚████║██╔══██║██║╚██╔╝██║██╔══╝░░██║░░██╗██╔══██║██╔══██║██║╚████║██║░░╚██╗██╔══╝░░██╔══██╗
#    ██████╔╝██║░╚███║██║░░██║██║░╚═╝░██║███████╗╚█████╔╝██║░░██║██║░░██║██║░╚███║╚██████╔╝███████╗██║░░██║
#    ╚═════╝░╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝░╚═════╝░╚══════╝╚═╝░░╚═╝
#
#         АВТОР ПЛАГИНА - skully [ https://skully.space ]
#
#                                            namechanger.CHANGERNAME
#               EXAMPLE: %namechanger.name%

changer:
  name: "This is your name"